services:
    happy_cms_menu.menu.repository:
        class: '%sylius_happy_cms.menu.menu.repository%'
        arguments:
            - '@doctrine'
            - '%sylius_happy_cms.menu.menu.class%'
        calls:
            - [ 'setConfig', [ '%sylius_happy_cms.menu.cache%' ] ]
        tags: [ doctrine.repository_service ]

    happy_cms_menu.menu_item.repository:
        class: '%sylius_happy_cms.menu.menu_item.repository%'
        arguments:
            - '@doctrine'
            - '%sylius_happy_cms.menu.menu_item.class%'
        calls:
            - [ 'setConfig', [ '%sylius_happy_cms.menu.cache%' ] ]
        tags: [ doctrine.repository_service ]

    Adeliom\SyliusHappyCMSPlugin\EventListener\Menu\MenuCreationListener:
        arguments:
            - '%sylius_happy_cms.menu.menu.class%'
            - '%sylius_happy_cms.menu.menu_item.class%'
            - '@sylius.locale_provider'
            - '@translator'
        tags:
            - # these are the options required to define the entity listener
                name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: '%sylius_happy_cms.menu.menu.class%'
                lazy: true

    Adeliom\SyliusHappyCMSPlugin\Twig\Menu\MenuExtension:
        public: true
        arguments:
            - '@twig'
            - '@doctrine.orm.entity_manager'
            - '%sylius_happy_cms.menu.menu.class%'
            - '%sylius_happy_cms.menu.menu_item.class%'
        tags:
            - { name: twig.extension }

    Adeliom\SyliusHappyCMSPlugin\Controller\MenuItem\MenuItemController:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%sylius_happy_cms.menu.menu_item.class%'
            - '@twig'
            - '@router'
        tags:
            - controller.service_arguments
