cmf_routing:
    chain:
        routers_by_id:
            router.default:             100
            cmf_routing.dynamic_router: 50
    dynamic:
        persistence:
            orm:
                enabled: true
        locales:
            - en_US
            - de_DE
            - fr_FR
            - es_ES
            - es_MX
            - pl_PL
            - pt_PT
            - zh_CN
        match_implicit_locale: false    
        controllers_by_class:
            Symfony\Cmf\Component\Routing\RedirectRouteInterface: cmf_routing.redirect_controller:redirectAction
            Symfony\Cmf\Component\Routing\RouteReferrersInterface: adeliom.sylius.cms.plugin.controller.render::renderAction
