sylius_twig_hooks:
  hooks:
    'sylius.shop.layout.head':
      seo_metas:
        template: "@SyliusHappyCMSPlugin/front/template_block/seo_metas.html.twig"

    'sylius.cms.shared_block.choose':
      content:
        template: "@SyliusHappyCMSPlugin/shared_block/select.html.twig"

    'sylius.cms.shared_block.create':
      content:
        template: "@SyliusAdmin/Crud/Create/_content.html.twig"

    'sylius_admin.happy_cms.medias':
      sidebar:
        template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
        priority: 200
      navbar:
        template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
        priority: 100
      manager:
        template: '@SyliusHappyCMSPlugin/media/manager.html.twig'
        priority: 0

    'sylius_admin.happy_cms.shared_block.select':
      sidebar:
        template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
        priority: 200
      navbar:
        template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
        priority: 100
      select_blocks:
        template: '@SyliusHappyCMSPlugin/shared_block/crud/select/blocks.html.twig'
        priority: 0

    'sylius_admin.page.index.content':
      flashes:
        template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
        priority: 300
      header:
        template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
        priority: 200
      grid:
        enabled: false
      sections:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/sections.html.twig'
        priority: 100
      footer:
        template: '@SyliusAdmin/shared/crud/common/content/footer.html.twig'
        priority: -100
    'sylius_admin.page.index.content.sections#left':
      tree:
        component: 'happycms-page-tree-tree'
        props:
          template: '@SyliusHappyCMSPlugin/page/crud/tree/components/tree.html.twig'
        priority: 0
    'sylius_admin.page.index.content.sections.tree':
      actions:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/actions.html.twig'
        priority: 0

    'sylius_admin.page.index.content.sections.tree.actions':
      edit:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/actions/edit.html.twig'
        priority: 100
      dropdown:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/actions/dropdown.html.twig'
        priority: 0
    'sylius_admin.page.index.content.sections.tree.actions.dropdown':
      create_child:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/actions/dropdown/create_child.html.twig'
        priority: 400
      delete:
        component: 'happycms-page-tree-delete'
        props:
          template: '@SyliusHappyCMSPlugin/page/crud/tree/components/delete.html.twig'
        priority: 300
      move_up:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/actions/dropdown/move_up.html.twig'
        priority: 100
      move_down:
        template: '@SyliusHappyCMSPlugin/page/crud/tree/actions/dropdown/move_down.html.twig'
        priority: 0
