sylius_happy_cms:
  page:
    page_class: "%sylius_happy_cms.page.model%"
    page_repository: "%sylius_happy_cms.page.repository%"
    page_admin: "%sylius_happy_cms.page.page_admin%"

  seo:
    title:
      suffix: ACME

  config:
    config_class: Adeliom\SyliusHappyCMSPlugin\Entity\Config\Config
    config_repository: Adeliom\SyliusHappyCMSPlugin\Repository\Config\ConfigRepository
    config_admin: Adeliom\SyliusHappyCMSPlugin\Admin\Config\ConfigAdmin

  menu:
    menu:
      class: Adeliom\SyliusHappyCMSPlugin\Entity\Menu\Menu
      repository: Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuRepository
    menu_item:
      class: Adeliom\SyliusHappyCMSPlugin\Entity\Menu\MenuItem
      repository: Adeliom\SyliusHappyCMSPlugin\Repository\Menu\MenuItemRepository

  media:
    storage_name: uploads.storage
    base_url: '/media/download'
    media_entity: Adeliom\SyliusHappyCMSPlugin\Entity\Media\Media
    folder_entity: Adeliom\SyliusHappyCMSPlugin\Entity\Media\Folder

  shared_block:
    shared_block_class: Adeliom\SyliusHappyCMSPlugin\Entity\SharedBlock\SharedBlock
    shared_block_repository: Adeliom\SyliusHappyCMSPlugin\Repository\SharedBlock\SharedBlockRepository
